#name: "Publish Javadoc"
#on:
#  push:
#    branches:
#      - master
#
#permissions:
#  contents: write
#
#jobs:
#  publish_javadoc:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Publish JavaDoc ðŸš€
#        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          javadoc-branch: javadoc
#          java-version: 17
#          target-folder: javadoc
#          project: maven
